import csv, pathlib
OUT = pathlib.Path(__file__).resolve().parent

# company, city, country, lifecycle, dealstage(空=案件なし), amount(JPY), samples, channel, note
C = [
("Itteki Matcha","Melbourne","Australia","customer","closedwon",1500000,"FA001,FA002,FA004,FA005x2","―","3店舗→10店舗計画。オーナーは元・豪州MUJI社長。銀行がメイン投資家でQC厳格。月合計228-241kg"),
("Cosecha","Gold Coast","Australia","customer","closedwon",30160000,"FA001,FA002,FA004,FA005,AFb,Cf,Dgx2,AFc,AEf,AFa,AEa","郵送","✅FA005 200kg×5週間ごと＝年2,080kg（2026-08-19確定）。¥14,500なら年¥30,160,000／定価¥15,000なら¥31,200,000。🔴FA005の引当が危険（Itteki3.2t＋Dens1.5t＋本件2.08t＝6.78t、Rockysは別）。¥14,500は下限割れで社内未承認"),
("Groove","Melbourne","Australia","customer","closedwon",0,"FA001-FA005","WhatsAppグループ","抹茶100g/日。10日以上のリードタイム不可"),
("Elle Collective","Claremont WA","Australia","customer","closedwon",625000,"FA002,FA003,FA004","電話","✅FA004 25kg受注（2026-08-19・¥625,000）。30g缶・80g缶の見積もり依頼あり（社内ボール=関谷くん）。追加25kgで計50kg・¥1,250,000。⚠️PayPal回答待ち。⚠️FA004はMOQ100kg引上げ方向で25kgは大きく下回る＝例外可否を要確認"),
("T2 Tea","Collingwood VIC","Australia","opportunity","contractsent",39000000,"―","―","FA002 1008kg/年・$260。契約書CFOレビュー中。B Corp＝完全トレーサビリティ必須。本社アポなし訪問禁止"),
("Sneaker Laundry","Melbourne","Australia","opportunity","decisionmakerboughtin",47250000,"FA003x2,FA004x2,FA005,AFc","―","FA003月175kg×12ヶ月。landed AUD236.4/kg DDP。8/14オーナー稟議の結果待ち。FA2.5も検討中"),
("JSY TEA","Surry Hills NSW","Australia","customer","closedwon",6750000,"―","E-mail","✅FA003 300kg受注（2026-08-18）。窓口Beiさん。🔴連絡先が未記録。⚠️当初想定1,000kgとの差700kgは未確定"),
("Matcha Mami","Chadstone VIC","Australia","opportunity","qualifiedtobuy",57600000,"FA001,FA002,FA003x2,FA004x2,FA005x3","E-mail","月50kg→新2店舗で月120-150kg。JPY建て5年契約の意向で一致。現行AUD173/kg。9月来日で茶園訪問"),
("Matcha Mate","Melbourne","Australia","opportunity","qualifiedtobuy",0,"―","―","既存顧客・Bb月100kg。協業の方向性のみ合意。数量・条件は未確定。US冷蔵庫アライアンスの相手"),
("O3","Newtown NSW","Australia","opportunity","qualifiedtobuy",0,"FA005,AEg","WhatsApp","FA003=ceremonial/AEa=culinary/AEh=hojicha に決定。80kg/3ヶ月。予算 landed A$180(reg)/A$200-230(prem)"),
("Kaori (Stephen)","Sydney","Australia","opportunity","contractsent",2250000,"1kgサンプル","WhatsAppグループ","FA003 100kg・9月第1週納品目標。PO方式・100%前金。🔴担当=Stephen(Steve Fambo)=Purematchaの窓口。Purematchaの60kg受注と同一案件かを要統合（二重計上の危険）"),
("Chatime Australia","Sydney NSW","Australia","salesqualifiedlead","appointmentscheduled",0,"―","E-mail","豪州170店超・年5t。2027年1月に再協議で合意。AUD120/kg FOB上限。即コンタクトしない"),
("Matcha Maiden","Caulfield South VIC","Australia","salesqualifiedlead","qualifiedtobuy",0,"サンプル+資料","電話","年4-6t。カスタムブレンド協業で合意。現行≈$60USD/kg。MOQ200kg/月。面談窓は木曜12-14時"),
("Tea Drop","Coburg East VIC","Australia","salesqualifiedlead","presentationscheduled",0,"FA001-FA005,AFb,Cf,Dg,AFc,AEf,AEg,Ij","E-mail","卸専門・創業22年。現行サプライヤーと15年。AFc（在庫10000kg）が本命"),
("Midori Matcha","Melbourne","Australia","salesqualifiedlead","qualifiedtobuy",0,"FA001-FA005","電話（架電営業）","月60kg・¥14,000-19,000/kg。八女を2年継続。少し安ければ移行意向。FA005が価格帯に合致"),
("MAMOT Solutions","","Australia","lead","",0,"―","E-mail","ディストリ・月100kg+（200kg検討）。価格重視。follow_up期日超過"),
("Purematcha","","Australia","customer","closedwon",1350000,"―","WhatsAppグループ","✅60kg受注（2026-08-19・⚠️SKUと単価は未記録／FA003なら¥1,350,000の試算）。担当=Stephen(Steve Fambo)。豪州最大級の抹茶卸・既に顧客。🔴Kaori名義の100kg案件と同一かを要統合"),
("TDH Milk","Sydney","Australia","lead","",0,"―","E-mail","現行JFC $90/kg・目標A$100-120。Cfで味比べ打診中。follow_up期日超過"),
("Tavalon","Molendinar QLD","Australia","lead","",0,"―","電話","Matthew Youn +61 430 006 064。⚠️Maison Koko Pty Ltd と同じ住所（Unit 2/3 Enterprise Street, Molendinar QLD 4214）。どちらの社名で提案するかを先に決めること"),
("Maison Koko Pty Ltd","Molendinar QLD","Australia","lead","",0,"―","電話","Unit 2/3 Enterprise Street, Molendinar QLD 4214（ゴールドコースト）。電話で折り返しあり・スーパーバイザー不在で再折り返し待ち。⚠️Tavalonと住所が重なる可能性を要確認。⭐Cosecha（Mermaid Waters QLD 4218・受注済み）と同エリア"),
("Morning Made","Auckland","New Zealand","lead","",0,"―","LinkedIn","NZ企業。店頭$59/60g＝A$983/kg。未接触。有機は宇治ではなく鹿児島を当てる"),
("Hello Matcha","Sydney NSW","Australia","salesqualifiedlead","",0,"Cf,AEf,FA005","WhatsApp","farm-direct宇治輸入卸・豪州1000+カフェ・年20t。US側で扱う（2026-08-18 Rui指示）"),
("Issho Cafe","Haymarket NSW","Australia","salesqualifiedlead","",0,"FA001,FA002,FA003","―","ドリンク$14＋席料$10。メニューに品種名おくみどり。16品全部抹茶。駅隣接"),
("The Tea Centre Pty Ltd","Brisbane QLD","Australia","salesqualifiedlead","",0,"FA003,FA004,FA005,AFa,AFb,De,Dg","WhatsApp","1993年創業・豪州東海岸10店舗＋オンライン。本社倉庫はブリスベン（訪問したPiccadillyはシドニーの1店舗）。缶小売逆算でプライスレンジ¥22,600-42,000/kg。⚠️未検証: Director=Simon Roy／年商約$6.2M"),
("BALIBOLA","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA004,Cf,AEf","個人WhatsApp","1日約200杯。自社ブランド缶RTDあり。カリナリーグレードを探し中"),
("Tori's","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA005","E-mail","5店舗グループ（Tori'sx2/Humble Rays/Suga Rays/Midday）。ほうじ茶缶あり。AEgは未配布"),
("Matcha Haus Okaeri","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA005","E-mail","RMIT Building 14内。1日約100食＝月9-15kg級。デザート業態＝Cfが本命"),
("Attakai Matcha","Melbourne CBD","Australia","salesqualifiedlead","",0,"FA001-FA004","Insta DM","1日約100杯。宇治＋静岡使用。缶小売あり。オーナー在店は月曜のみ・13時前"),
("Hikari Cafe","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA004","―","317 Swanston St。京都の小農園から仕入れ・手点てceremonialの本格派。Derekが東京の展示会に来訪済"),
("Kona Matcha","South Yarra VIC","Australia","lead","",0,"FA001-FA005","E-mail","オーナーは日本人。⚠️競合でもある（豪州の抹茶サプライヤー）。未連絡。現行仕入元を要確認"),
("OSOI","Brunswick VIC","Australia","salesqualifiedlead","",0,"FA001-FA005,AEg,Ij","WhatsApp","TikTokで待ち1時間超。全て手点て。標準ラテはさえみどりのプレミアムブレンド"),
("ICE KO-II","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA005","Insta DM","抹茶を4段階の濃さで出し分け。ジェラート・かき氷・餅。ほうじ茶もあり"),
("St Ali / Clement / Peggies","Melbourne","Australia","salesqualifiedlead","",0,"FA001-FA005,AFc,Cf","E-mail","コーヒーロースター大手グループ。1社取ればグループ横展開"),
("Little Rogue","Melbourne CBD","Australia","salesqualifiedlead","",0,"FA001-FA005","Insta DM","抹茶ラテが看板。抹茶パウダーを袋で小売。ほうじ茶ラテ・抹茶ブラウニー"),
("MINIYAMA","Chadstone VIC","Australia","salesqualifiedlead","",0,"FA001,FA002,FA003x2,FA004x2,FA005x2","E-mail","抹茶がbest-seller・豆乳対応。オーナー在店は水曜"),
("Miyama","Melbourne CBD","Australia","salesqualifiedlead","",0,"FA001-FA004","E-mail","Melbourne Central L2。日本カレー＋抹茶。次の社内MTGで提案予定"),
("KUMO","Melbourne CBD","Australia","salesqualifiedlead","",0,"FA001-FA005","Insta DM","スフレパンケーキ＋抹茶。同オーナーが KUMO Brewhouse も運営"),
("MEET FOREST","South Yarra VIC","Australia","lead","",0,"FA003,FA005","メール","halal-friendly。製菓主体。未連絡"),
("Mado Matcha","Sydney","Australia","salesqualifiedlead","",0,"FA004,FA003,De,AFb,AEa,AFa,Dg","―","414 Elizabeth St・Central駅2分の小箱。FA2.5送付予定"),
("Naau Cafe","Melbourne","Australia","lead","",0,"FA001-FA004","Insta DM","276 Russell St。コーヒー先行。オーナー在店は火・水"),
("TAKEZO","Melbourne","Australia","lead","",0,"AFb,AFc","―","高級寿司店。抹茶の数量は期待薄。本命は他店への紹介ルート"),
("JIBBI Coffee Roasters","Sydney","Australia","lead","",0,"FA002,AEa,De,Dg,AFb,AFa","―","ロースター。担当者名・連絡先が未記録"),
("Regulars","Melbourne CBD","Australia","lead","",0,"FA001-FA004","E-mail","フレーバー先行（ピスタチオ抹茶/Nordic berry抹茶）"),
("Bench Coffee","Melbourne","Australia","lead","",0,"AFb,Cf","―","ゆうかさん経由"),
("karomi cafe","Melbourne","Australia","other","",0,"FA003,FA004,FA005","E-mail","2店舗＝19 MacKenzie St ＋ 9 Baskerville Lane。⚠️ITTEKI MATCHAから仕入れ中＝頭越し注意。お礼のみで提案しない"),
("OKO Cafe","Melbourne","Australia","lead","",0,"FA003,FA004,FA005","―",""),
("Puzzle Coffee","Melbourne","Australia","lead","",0,"FA003,FA004,FA005","―",""),
("A3","Central Park NSW","Australia","lead","",0,"FA003,FA004,FA005","―","宇治抹茶使用"),
("T TOTALER","Marrickville NSW","Australia","salesqualifiedlead","",0,"FA003,FA004,FA005,Cf,AEg,Ij","電話","豪州の茶ブランド AUSTRALIAN MADE TEA。62 Shepherd St, Marrickville NSW 2204＋直営店 RG26A The Galeries, 500 George St Sydney。新規開拓リストの卸と同一"),
("Social Butterfly Tea & Dessert","Sydney","Australia","lead","",0,"FA003,FA004,FA005","―","デザート業態"),
("OFFSET Matcha & Brew","Surry Hills NSW","Australia","lead","",0,"AFb,De","E-mail","⚠️メールの綴りは要確認（名刺の手書き）"),
("Simply Native","Surry Hills NSW","Australia","lead","",0,"―","―","新規開拓リストでFA001ド本命指定。訪問記録なし"),
("ellu cafe","Surry Hills NSW","Australia","lead","",0,"―","―","現行は和光（丸久小山園の宇治抹茶）。店内4テーブルの小箱。訪問記録なし"),
("Kuuki Cafe","Sunshine VIC","Australia","lead","",0,"―","Insta DM","姉妹経営。現行は静岡から仕入れ。未接触"),
("Matcha Society","","Australia","lead","",0,"FA001,FA002,FA003,FA005","E-mail","郵送済・反応待ち"),
("Midori pop-up","Fitzroy VIC","Australia","lead","",0,"FA001-FA005","電話","Rose St マーケット。Joanna&RitaがMatthew用に預かり"),
("Deiji Matcha","Melbourne","Australia","other","closedlost",0,"FA001-FA004,AFb","Insta DM","❌失注（2026-08-18）。月5-20kg・30g缶リテール希望だった新興先"),
("Hareruya","Melbourne CBD","Australia","other","closedlost",0,"FA001-FA004","メール","❌失注。1日300-500杯。メールにて返信あり＝明確な辞退"),
("Zen Wonders","Melbourne","Australia","other","closedlost",0,"FA001-FA005,AFb,Cf,Dg,AFc,AEf","―","❌失注（競合リスク）。単価上限¥20,000。サンプル10本投下"),
("ima Asa Yoru","Brunswick VIC","Australia","other","closedlost",0,"AFb","E-mail","❌失注（MOQ未達）。ima Pantry併設＝リテール枠の芽"),
("Astrid","Melbourne","Australia","other","closedlost",0,"―","―","❌低優先。月1-2kgでMOQ20kgに合わず。サンプル未配布"),
("Analytical Laboratories & Technical Services Australia","Merbein South VIC","Australia","lead","",0,"FA001,FA002,FA003","WhatsApp","検査ラボ。7/2発送→1ヶ月超ノーレス。実需が不明"),
("Levalicious","","Australia","lead","",0,"―","WhatsApp/E-mail","50-100kg。下書き止まり・期日超過"),
("YOWHIRL","","Australia","lead","",0,"―","WhatsApp","10-50kg。下書き止まり・期日超過"),
("CloudHaus cafe","","Australia","lead","",0,"―","WhatsApp","10-50kg。下書き止まり・期日超過"),
("C2 matcha","","Australia","lead","",0,"―","E-mail","5-10kg。ポップアップ＋オンライン。14種と約束しない"),
]
# 氏名, 姓, 役職, 決裁権, email, phone, 会社, lifecycle, leadstatus, 言語, note
P = [
("Calder","Dryden","","決裁者","","","Cosecha","customer","OPEN_DEAL","English","メール・電話とも未記録。送付先住所のみ判明"),
("Sunny","","オーナー","決裁者","","","Groove","customer","OPEN_DEAL","English","WhatsAppグループ作成済（番号未記録）。パートナーと共同決裁"),
("Ellie","Dunne","","決裁者","","+61 437 900 130","Elle Collective","customer","OPEN_DEAL","English","FA004受注。PayPal決済希望"),
("Olivia","","Head of Buying","決裁者","","","T2 Tea","opportunity","OPEN_DEAL","English","窓口は長野代表がリード。最終承認はCFO"),
("Emma","","Junior Buyer","取次ぎ","","","T2 Tea","opportunity","IN_PROGRESS","English","日常のやりとり担当"),
("Eugene","","オーナー","決裁者","","","Sneaker Laundry","opportunity","OPEN_DEAL","English","稟議の最終判断。窓口はNick経由"),
("Nick","","","取次ぎ","","","Sneaker Laundry","opportunity","IN_PROGRESS","English",""),
("Bei","","","要確認","ka.mi.surryhills@gmail.com","","JSY TEA","customer","OPEN_DEAL","","✅受注（FA003 300kg・¥675万）。⚠️メールの ka.mi が社名・担当者名と一致しないため、出荷・請求の連絡前に本人確認すること"),
("Rachel","","","決裁者","","+61 412 596 694","O3","opportunity","OPEN_DEAL","English","WhatsApp。全サプライヤーを試して First Agri に決定"),
("Stephen","Fambo","","決裁者","","","Purematcha","customer","OPEN_DEAL","English","✅Purematchaの担当者（2026-08-19判明）。60kg受注。WhatsAppグループで連絡。⚠️Offsetの Stephan とは別人。🔴Kaori名義の100kg案件と同一かを要統合"),
("Zahraa","","オーナー","決裁者","","","Matcha Mami","opportunity","OPEN_DEAL","English","家族経営。9月来日で茶園訪問予定"),
("Nabil","","窓口兼投資家","取次ぎ","nabil@nonstop-media.com.au","","Matcha Mami","opportunity","IN_PROGRESS","English","実務のやりとりはここ経由"),
("Ken","","CFO兼CMO","決裁者","","","Matcha Mate","opportunity","OPEN_DEAL","","⚠️Little RogueのKenとは別人。連絡先が未記録"),
("Chen","","","取次ぎ","","","Matcha Mate","opportunity","IN_PROGRESS","","物流・管理費の協議相手"),
("Ricky","","共同創業者クラス","決裁者","","","Hello Matcha","salesqualifiedlead","IN_PROGRESS","English","⚠️連絡先なし。US側で扱う"),
("Ami","","共同創業者","決裁者","","","Hello Matcha","salesqualifiedlead","IN_PROGRESS","English",""),
("Danny","He","","決裁者","danny.he@chatimeGroup.com.au","+61 421 526 695","Chatime Australia","salesqualifiedlead","BAD_TIMING","English","2027年1月まで動かない。即コンタクトしない"),
("Dylan","Nadelman","CEO","決裁者","","+61 432 011 928","Matcha Maiden","salesqualifiedlead","IN_PROGRESS","English","面談窓は木曜12-14時"),
("Jeff","Nadelman","オーナー","決裁者","","","Matcha Maiden","salesqualifiedlead","IN_PROGRESS","English",""),
("Jasmine","","品質/テイストマスター","取次ぎ","","","Matcha Maiden","salesqualifiedlead","IN_PROGRESS","English","🔑カスタムブレンドの味の合否を握るキーパーソン"),
("Grenville","Rodrigues","Operations Manager","取次ぎ","grenville@matchamaiden.com","+61 410 098 525","Matcha Maiden","salesqualifiedlead","IN_PROGRESS","English","サンプル送受の窓口"),
("Mevan","","","取次ぎ","Mevan@teadrop.com.au","+61 491 269 876","Tea Drop","salesqualifiedlead","IN_PROGRESS","English","8/10本社商談。Ruiとともに過去ドバイ在住"),
("Helen","Samaras","","取次ぎ","helen@teadrop.com.au","","Tea Drop","salesqualifiedlead","UNQUALIFIED","English","7/31メールがノーレス。Mevanを主窓口に切替"),
("Ashok","Dias","創業者","決裁者","","","Tea Drop","salesqualifiedlead","NEW","English","未面会"),
("Tina","Denkova","","要確認","tina@mamot.com.au","+61 420 990 343","MAMOT Solutions","lead","ATTEMPTED_TO_CONTACT","English","期日超過"),
("Matthew","","","決裁者","","","Midori Matcha","salesqualifiedlead","IN_PROGRESS","English","⚠️電話済だが番号が未記録。ベトナム拠点の可能性"),
("Joanna","","","情報提供者","","","Midori pop-up","lead","NEW","English","Rita と2名でスタンド対応"),
("Ryan","Tran","","要確認","tdh70696@gmail.com","+61 414 189 849","TDH Milk","lead","ATTEMPTED_TO_CONTACT","English","期日超過"),
("Angela","","経営者","決裁者","","","Deiji Matcha","other","UNQUALIFIED","English","❌失注"),
("Matthew","Youn","","要確認","","+61 430 006 064","Tavalon","lead","ATTEMPTED_TO_CONTACT","English","✅2026-08-19: 所属は Tavalon（Maison Kokoではない）。両社は同住所"),
("Stephany","","Procurement","取次ぎ","hello@maisonkoko.com","","Maison Koko Pty Ltd","lead","ATTEMPTED_TO_CONTACT","English","再折り返し待ち"),
("Brad","Matthews","創業者/Director","決裁者","","","Morning Made","lead","NEW","English","LinkedIn bradcm01 で接触。未接触"),
("Sterra","","スタッフ","取次ぎ","","","Attakai Matcha","salesqualifiedlead","IN_PROGRESS","English","オーナーへ取次ぎ中"),
("Zara","","オーナー","決裁者","","+61 428 314 275","BALIBOLA","salesqualifiedlead","IN_PROGRESS","English","ご両親との家族経営＝実質3人の合議"),
("Yuka","","スタッフ","情報提供者","","","BALIBOLA","salesqualifiedlead","IN_PROGRESS","Japanese","群馬出身の日本人。⚠️Bench Coffeeのゆうかさんと同一人物か要確認"),
("Nahm","","","決裁者","hello@toris.com.au","","Tori's","salesqualifiedlead","IN_PROGRESS","English","Tori's側の責任者"),
("Sutinee","Suntivatana","グループ創業者","決裁者","","","Tori's","salesqualifiedlead","IN_PROGRESS","English","Tinee Su。5店舗グループの最上位決裁者"),
("Chyanne","","","取次ぎ","","","Tori's","salesqualifiedlead","IN_PROGRESS","English",""),
("Takafumi","Kumayama","","要確認","takahumik@hotmail.com","+61 421 366 817","Matcha Haus Okaeri","salesqualifiedlead","NEW","Japanese","熊山貴文。⚠️本人には未面会。オーナー名も未確認"),
("Eddy","","オーナー","決裁者","","","Kona Matcha","lead","NEW","Japanese","日本人。未連絡。⚠️競合でもある"),
("Meta","","スタッフ","取次ぎ","","","Kona Matcha","lead","NEW","English","Eddyへ取次ぎ"),
("SHY","","オーナー","決裁者","","+61 422 685 099","OSOI","salesqualifiedlead","IN_PROGRESS","English","ご夫婦で創業。旦那さまは弁護士＝条件は細かく詰められる前提"),
("Sharo","","オーナー","決裁者","","+61 424 134 887","ICE KO-II","salesqualifiedlead","IN_PROGRESS","","⚠️英字綴りは要確認（しゃろーさん）"),
("Ken","","","取次ぎ","","","Little Rogue","salesqualifiedlead","IN_PROGRESS","English","⚠️Matcha MateのKenとは別人"),
("Derek","Yang","Business Development Co-founder","決裁者","derek@hikarilife.com.au","+61 431 483 067","Hikari Cafe","salesqualifiedlead","IN_PROGRESS","English","6月の東京・輸出EXPOで弊社ブースに来訪済＝既接点あり"),
("Gracia","","","取次ぎ","","","KUMO","salesqualifiedlead","ATTEMPTED_TO_CONTACT","English","IG DM済みで返信なし"),
("Kei","","店長","取次ぎ","info@miyamamelbourne.com.au","","Miyama","salesqualifiedlead","IN_PROGRESS","Japanese","次の社内MTGで提案予定"),
("Sofi","","マネージャー","取次ぎ","","","St Ali / Clement / Peggies","salesqualifiedlead","IN_PROGRESS","Japanese","さとこ。日本人マネージャー＝決裁に近い窓口"),
("Sal","","創業者/オーナー","決裁者","","","St Ali / Clement / Peggies","salesqualifiedlead","NEW","English","Salvatore。普段イタリア在住・豪州へ3ヶ月に1回"),
("Ross","","GM","決裁者","","","St Ali / Clement / Peggies","salesqualifiedlead","NEW","English","店に週2-3回来る"),
("Hannah","","","要確認","hannahliu513@gmail.com","","MEET FOREST","lead","NEW","English","未連絡。halal-friendly＝認証で攻める"),
("Emily","","","要確認","","","Mado Matcha","salesqualifiedlead","IN_PROGRESS","","エミリー。FA2.5送付予定。⚠️連絡先が未記録"),
("Takeshi","","","決裁者","","","TAKEZO","lead","IN_PROGRESS","Japanese","たけしさん。Ruiの寿司職人の先輩。本命は紹介ルート"),
("Tomoya","","カフェ勤務","情報提供者","","","","lead","IN_PROGRESS","Japanese","TOMOYA君。⚠️勤務先のカフェ名が未記録"),
("Ako","","オーナー","決裁者","hello@imacafe.co","","ima Asa Yoru","other","UNQUALIFIED","Japanese","❌失注（MOQ未達）"),
("Robert","","オーナー","決裁者","","","Zen Wonders","other","UNQUALIFIED","English","❌失注。長野代表と旧知。単価上限¥20,000"),
("Kantaro","","オーナー","決裁者","","","Hareruya","other","UNQUALIFIED","Japanese","❌失注。NZ出身の日本人。日本食10店舗弱"),
("Jaya","Rajan","","要確認","","+61 409 213 706","Analytical Laboratories & Technical Services Australia","lead","ATTEMPTED_TO_CONTACT","English","1ヶ月超ノーレス。クローズ質問1本で生死判定"),
("Levae","Ziaei","","要確認","info@levalicious.com.au","+61 403 471 443","Levalicious","lead","NEW","English","下書き止まり・期日超過"),
("Po Wei","Su","","要確認","chisame7@gmail.com","+61 422 461 933","YOWHIRL","lead","NEW","English","下書き止まり・期日超過"),
("Vinca","Chainiago","","要確認","vincachainiago1@yahoo.com.au","+61 403 770 082","CloudHaus cafe","lead","NEW","English","下書き止まり・期日超過"),
("Stephan","","","取次ぎ","offset.surryhills@gmail.com","","OFFSET Matcha & Brew","lead","NEW","English","⚠️メールの綴りは名刺の手書きのため要確認。⚠️Kaori の Stephen（Steve Fambo）と同一人物の可能性が高い"),
("Lucie","","店舗スタッフ（シドニーCBD）","情報提供者","","+61 401 765 311","The Tea Centre Pty Ltd","salesqualifiedlead","IN_PROGRESS","English","8/17にWhatsApp交換。🔴シドニーCBD店舗のスタッフ＝決裁者ではない。本社/倉庫はブリスベン＝卸の話は本部ルートが別に要る"),
("Thomas","Weston","オーナー","決裁者","karomicafe@outlook.com","","karomi cafe","other","NEW","English","🔴ITTEKI MATCHA経由で仕入れ中＝直接の提案をしない。お礼のみ"),
("Amber","Sunderland","","要確認","","+61 466 436 302","T TOTALER","salesqualifiedlead","NEW","English","豪州の茶ブランド AUSTRALIAN MADE TEA。直営ティーショップあり（The Galeries, 500 George St）"),
("Sophie","Nguyen","","要確認","soph.n2308@gmail.com","+61 469 035 234","C2 matcha","lead","NEW","English","14種と約束しない。FA 5SKUのキュレーションで返す"),
]

with open(OUT/"hubspot-companies.csv","w",newline="",encoding="utf-8-sig") as f:
    w=csv.writer(f); w.writerow(["Company name","City","Country/Region","Lifecycle Stage",
        "FA_配布サンプル","FA_連絡チャネル","FA_豪州出張メモ"])
    for n,city,ctry,lc,_,_,smp,ch,note in C: w.writerow([n,city,ctry,lc,smp,ch,note])

with open(OUT/"hubspot-contacts.csv","w",newline="",encoding="utf-8-sig") as f:
    w=csv.writer(f); w.writerow(["First Name","Last Name","Email","Phone Number","Job Title",
        "Company name","Lifecycle Stage","Lead Status","FA_決裁権","FA_対応言語","FA_豪州出張メモ"])
    for fn,ln,title,auth,em,ph,co,lc,ls,lang,note in P:
        assert fn or ln, f"HubSpotは氏名かEmailが無いとコンタクトを作れない: {co}"
        w.writerow([fn,ln,em,ph,title,co,lc,ls,auth,lang,note])

with open(OUT/"hubspot-deals.csv","w",newline="",encoding="utf-8-sig") as f:
    w=csv.writer(f); w.writerow(["Deal name","Deal stage","Amount","Currency",
        "Associated company","FA_確度メモ"])
    for n,_,_,_,st,amt,_,_,note in C:
        if not st: continue
        w.writerow([f"{n} — 豪州2026",st,amt if amt else "",'JPY',n,note])
print("companies",len(C),"/ contacts",len(P),"/ deals",len([1 for c in C if c[4]]))
