"""
Deal universe — initial seed of 60 companies across 5 sectors.
All profiles are fictional archetypes based on real market patterns.
Replace/augment with real data from INITIAL, PR TIMES, etc.

Sectors:
  1. 医療・介護AI        (12 companies)
  2. 建設・不動産テック   (12 companies)
  3. SMB向け金融インフラ  (12 companies)
  4. サプライチェーン・物流AI (12 companies)
  5. 法務・バックオフィス  (12 companies)
"""

UNIVERSE: list[dict] = [

    # ══════════════════════════════════════════════════════════════
    # SECTOR 1: 医療・介護AI  ← 最高確信度
    # ══════════════════════════════════════════════════════════════

    {
        "id": "med_001", "name": "CareLink AI", "sector": "医療・介護AI",
        "stage": "Series B", "hq": "東京", "founded": 2021,
        "description": "介護施設向けAIケアプランニング＆スタッフ最適化SaaS。厚労省認定取得。",
        "website": "carelinkj.example.com", "source": "simulation",
        "metrics": {"arr_mn_jpy": 420, "growth_yoy_pct": 165, "gross_margin": 78,
                    "nrr_pct": 118, "cac_months": 11, "runway_months": 18,
                    "employees": 52, "tam_bn_jpy": 200},
    },
    {
        "id": "med_002", "name": "MediPath AI", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "大阪", "founded": 2020,
        "description": "病院向けAI診断支援 + 電子カルテ自動入力。放射線科特化。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 180, "growth_yoy_pct": 210, "gross_margin": 80,
                    "nrr_pct": 122, "cac_months": 14, "runway_months": 15,
                    "employees": 28, "tam_bn_jpy": 300},
    },
    {
        "id": "med_003", "name": "PharmaSense", "sector": "医療・介護AI",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "製薬企業向けAI創薬候補探索 + 副作用予測プラットフォーム。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 650, "growth_yoy_pct": 88, "gross_margin": 85,
                    "nrr_pct": 130, "cac_months": 18, "runway_months": 24,
                    "employees": 90, "tam_bn_jpy": 1200},
    },
    {
        "id": "med_004", "name": "NurseFlow", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "福岡", "founded": 2022,
        "description": "看護師の業務記録をAI自動化。夜勤ストレス軽減。病院チェーン特化。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 95, "growth_yoy_pct": 290, "gross_margin": 75,
                    "nrr_pct": 115, "cac_months": 9, "runway_months": 14,
                    "employees": 18, "tam_bn_jpy": 80},
    },
    {
        "id": "med_005", "name": "CognitiveCare", "sector": "医療・介護AI",
        "stage": "Seed", "hq": "東京", "founded": 2023,
        "description": "認知症早期検知AIアプリ。MCI（軽度認知障害）をスマホで検知。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 25, "growth_yoy_pct": 400, "gross_margin": 82,
                    "nrr_pct": 108, "cac_months": 6, "runway_months": 18,
                    "employees": 12, "tam_bn_jpy": 150},
    },
    {
        "id": "med_006", "name": "RehabAI", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "名古屋", "founded": 2021,
        "description": "リハビリ施設向けAI回復予測＆プログラム最適化。保険適用データ連携。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 140, "growth_yoy_pct": 175, "gross_margin": 76,
                    "nrr_pct": 119, "cac_months": 12, "runway_months": 16,
                    "employees": 24, "tam_bn_jpy": 120},
    },
    {
        "id": "med_007", "name": "ClinicBot", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "東京", "founded": 2020,
        "description": "クリニック向けAI予約・問診・会計自動化。OpenAPI対応。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 310, "growth_yoy_pct": 120, "gross_margin": 71,
                    "nrr_pct": 112, "cac_months": 8, "runway_months": 20,
                    "employees": 45, "tam_bn_jpy": 180},
    },
    {
        "id": "med_008", "name": "SeniorLink", "sector": "医療・介護AI",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "在宅介護家族向けプラットフォーム。AI見守りセンサー＋家族アプリ。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 520, "growth_yoy_pct": 95, "gross_margin": 68,
                    "nrr_pct": 114, "cac_months": 15, "runway_months": 22,
                    "employees": 75, "tam_bn_jpy": 250},
    },
    {
        "id": "med_009", "name": "MentalScope", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "企業向けメンタルヘルスAI早期発見プラットフォーム。EAP連携。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 160, "growth_yoy_pct": 220, "gross_margin": 80,
                    "nrr_pct": 125, "cac_months": 10, "runway_months": 18,
                    "employees": 30, "tam_bn_jpy": 90},
    },
    {
        "id": "med_010", "name": "PathologyAI", "sector": "医療・介護AI",
        "stage": "Series B", "hq": "京都", "founded": 2018,
        "description": "病理画像AIスキャン。がん検診の精度を向上。大学病院と共同開発。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 890, "growth_yoy_pct": 72, "gross_margin": 88,
                    "nrr_pct": 135, "cac_months": 20, "runway_months": 30,
                    "employees": 120, "tam_bn_jpy": 800},
    },
    {
        "id": "med_011", "name": "PharmaConnect", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "大阪", "founded": 2021,
        "description": "薬局向けAI在庫管理＋患者フォローアップ自動化。調剤チェーン特化。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 220, "growth_yoy_pct": 145, "gross_margin": 74,
                    "nrr_pct": 116, "cac_months": 11, "runway_months": 17,
                    "employees": 38, "tam_bn_jpy": 130},
    },
    {
        "id": "med_012", "name": "CareMetrics", "sector": "医療・介護AI",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "介護施設経営者向けKPIダッシュボード＋AI経営アドバイザリー。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 75, "growth_yoy_pct": 310, "gross_margin": 83,
                    "nrr_pct": 121, "cac_months": 7, "runway_months": 16,
                    "employees": 15, "tam_bn_jpy": 60},
    },

    # ══════════════════════════════════════════════════════════════
    # SECTOR 2: 建設・不動産テック
    # ══════════════════════════════════════════════════════════════

    {
        "id": "con_001", "name": "BuildSense", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "大阪", "founded": 2020,
        "description": "建設現場向けAI安全管理＆工程最適化SaaS。BIMネイティブ。",
        "website": "", "source": "simulation",
        "metrics": {"arr_mn_jpy": 210, "growth_yoy_pct": 210, "gross_margin": 72,
                    "nrr_pct": 124, "cac_months": 8, "runway_months": 12,
                    "employees": 35, "tam_bn_jpy": 500},
    },
    {
        "id": "con_002", "name": "EstimAI", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "中小ゼネコン向けAI工事積算自動化。見積もり工数▲80%。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 155, "growth_yoy_pct": 195, "gross_margin": 76,
                    "nrr_pct": 120, "cac_months": 10, "runway_months": 14,
                    "employees": 22, "tam_bn_jpy": 200},
    },
    {
        "id": "con_003", "name": "SiteWatch", "sector": "建設・不動産テック",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "ドローン＋AIによる建設現場進捗管理。写真測量と工程比較。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 480, "growth_yoy_pct": 102, "gross_margin": 70,
                    "nrr_pct": 118, "cac_months": 13, "runway_months": 20,
                    "employees": 68, "tam_bn_jpy": 350},
    },
    {
        "id": "con_004", "name": "PropertyAI", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "東京", "founded": 2020,
        "description": "不動産売買AIマッチング＆価格査定。仲介会社向けSaaS。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 280, "growth_yoy_pct": 130, "gross_margin": 78,
                    "nrr_pct": 113, "cac_months": 12, "runway_months": 18,
                    "employees": 42, "tam_bn_jpy": 400},
    },
    {
        "id": "con_005", "name": "FacilityBot", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "名古屋", "founded": 2021,
        "description": "ビルオーナー向けAI設備管理＆予知保全。IoTセンサー統合。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 190, "growth_yoy_pct": 165, "gross_margin": 73,
                    "nrr_pct": 117, "cac_months": 11, "runway_months": 15,
                    "employees": 31, "tam_bn_jpy": 280},
    },
    {
        "id": "con_006", "name": "CivicMap", "sector": "建設・不動産テック",
        "stage": "Series B", "hq": "東京", "founded": 2018,
        "description": "自治体向けインフラ点検AIシステム。橋梁・トンネルの亀裂検知。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 720, "growth_yoy_pct": 78, "gross_margin": 82,
                    "nrr_pct": 125, "cac_months": 22, "runway_months": 28,
                    "employees": 95, "tam_bn_jpy": 600},
    },
    {
        "id": "con_007", "name": "RenovAI", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "リノベーション施工会社向けAI見積＆工程管理。B2B SaaS。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 85, "growth_yoy_pct": 340, "gross_margin": 74,
                    "nrr_pct": 116, "cac_months": 7, "runway_months": 16,
                    "employees": 16, "tam_bn_jpy": 150},
    },
    {
        "id": "con_008", "name": "SmartZone", "sector": "建設・不動産テック",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "商業施設テナント管理AI。賃料最適化＋空室予測。REIT運用向け。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 560, "growth_yoy_pct": 88, "gross_margin": 79,
                    "nrr_pct": 121, "cac_months": 16, "runway_months": 22,
                    "employees": 74, "tam_bn_jpy": 450},
    },
    {
        "id": "con_009", "name": "HousingFlow", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "福岡", "founded": 2021,
        "description": "住宅建設会社向けAI顧客管理＆契約自動化。地場工務店特化。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 120, "growth_yoy_pct": 220, "gross_margin": 75,
                    "nrr_pct": 114, "cac_months": 9, "runway_months": 13,
                    "employees": 20, "tam_bn_jpy": 100},
    },
    {
        "id": "con_010", "name": "WorkerTrack", "sector": "建設・不動産テック",
        "stage": "Series A", "hq": "大阪", "founded": 2020,
        "description": "建設作業員の入退場管理＆資格証書類AI管理。コンプライアンス自動化。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 170, "growth_yoy_pct": 155, "gross_margin": 71,
                    "nrr_pct": 115, "cac_months": 10, "runway_months": 17,
                    "employees": 28, "tam_bn_jpy": 180},
    },
    {
        "id": "con_011", "name": "EnergyBIM", "sector": "建設・不動産テック",
        "stage": "Series B", "hq": "東京", "founded": 2018,
        "description": "建物エネルギー消費AI最適化。ZEB（ゼロエネルギービル）認証支援。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 390, "growth_yoy_pct": 98, "gross_margin": 77,
                    "nrr_pct": 119, "cac_months": 15, "runway_months": 24,
                    "employees": 55, "tam_bn_jpy": 320},
    },
    {
        "id": "con_012", "name": "ConstructDesk", "sector": "建設・不動産テック",
        "stage": "Seed", "hq": "東京", "founded": 2023,
        "description": "建設会社バックオフィスAI自動化（請求書・日報・労務管理）。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 30, "growth_yoy_pct": 500, "gross_margin": 80,
                    "nrr_pct": 112, "cac_months": 5, "runway_months": 20,
                    "employees": 10, "tam_bn_jpy": 80},
    },

    # ══════════════════════════════════════════════════════════════
    # SECTOR 3: SMB向け金融インフラ
    # ══════════════════════════════════════════════════════════════

    {
        "id": "fin_001", "name": "LoanForge", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "東京", "founded": 2023,
        "description": "中小企業向けAI融資審査プラットフォーム（銀行・信金向けSaaS）。",
        "website": "", "source": "simulation",
        "metrics": {"arr_mn_jpy": 85, "growth_yoy_pct": 280, "gross_margin": 81,
                    "nrr_pct": 131, "cac_months": 18, "runway_months": 22,
                    "employees": 32, "tam_bn_jpy": 1500},
    },
    {
        "id": "fin_002", "name": "InvoiceFlow", "sector": "SMB向け金融インフラ",
        "stage": "Series B", "hq": "東京", "founded": 2020,
        "description": "中小企業向けAI請求書ファクタリング＆早期資金化。即日審査。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 430, "growth_yoy_pct": 118, "gross_margin": 65,
                    "nrr_pct": 128, "cac_months": 6, "runway_months": 18,
                    "employees": 58, "tam_bn_jpy": 2000},
    },
    {
        "id": "fin_003", "name": "TaxSense", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "中小企業向けAI税務自動化（インボイス対応）。税理士補助ツール。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 260, "growth_yoy_pct": 148, "gross_margin": 78,
                    "nrr_pct": 116, "cac_months": 8, "runway_months": 16,
                    "employees": 40, "tam_bn_jpy": 300},
    },
    {
        "id": "fin_004", "name": "PayrollAI", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "大阪", "founded": 2021,
        "description": "中小企業向けAI給与計算＋人事・労務管理。社労士API連携。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 195, "growth_yoy_pct": 168, "gross_margin": 76,
                    "nrr_pct": 114, "cac_months": 9, "runway_months": 15,
                    "employees": 35, "tam_bn_jpy": 220},
    },
    {
        "id": "fin_005", "name": "CreditScope", "sector": "SMB向け金融インフラ",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "小売・飲食業向けAI売掛金管理＆与信スコアリング。POS連携。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 580, "growth_yoy_pct": 90, "gross_margin": 72,
                    "nrr_pct": 122, "cac_months": 11, "runway_months": 24,
                    "employees": 80, "tam_bn_jpy": 800},
    },
    {
        "id": "fin_006", "name": "BankBridge", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "地銀向けオープンバンキングAPI基盤。SMBのデータをFinTechに開放。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 110, "growth_yoy_pct": 240, "gross_margin": 83,
                    "nrr_pct": 127, "cac_months": 16, "runway_months": 20,
                    "employees": 22, "tam_bn_jpy": 600},
    },
    {
        "id": "fin_007", "name": "ExpenseBot", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "中小企業向けAI経費精算自動化。レシートOCR＋承認ワークフロー。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 145, "growth_yoy_pct": 185, "gross_margin": 79,
                    "nrr_pct": 115, "cac_months": 7, "runway_months": 17,
                    "employees": 25, "tam_bn_jpy": 180},
    },
    {
        "id": "fin_008", "name": "CashFlow AI", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "名古屋", "founded": 2022,
        "description": "中小製造業向けAI資金繰り予測＆自動借入申請。3ヶ月先を可視化。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 70, "growth_yoy_pct": 320, "gross_margin": 81,
                    "nrr_pct": 118, "cac_months": 8, "runway_months": 14,
                    "employees": 14, "tam_bn_jpy": 400},
    },
    {
        "id": "fin_009", "name": "AgriFinance", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "北海道", "founded": 2021,
        "description": "農業法人向けAI農業融資審査＆収益管理。JAとの連携。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 90, "growth_yoy_pct": 260, "gross_margin": 74,
                    "nrr_pct": 120, "cac_months": 13, "runway_months": 18,
                    "employees": 18, "tam_bn_jpy": 200},
    },
    {
        "id": "fin_010", "name": "InsureTech Japan", "sector": "SMB向け金融インフラ",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "中小企業向けオンデマンド型ビジネス保険AI。リスクに応じた動的プライシング。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 340, "growth_yoy_pct": 105, "gross_margin": 68,
                    "nrr_pct": 119, "cac_months": 10, "runway_months": 22,
                    "employees": 48, "tam_bn_jpy": 700},
    },
    {
        "id": "fin_011", "name": "GrantAI", "sector": "SMB向け金融インフラ",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "中小企業の補助金・助成金申請をAIが自動マッチング＆書類作成。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 55, "growth_yoy_pct": 380, "gross_margin": 85,
                    "nrr_pct": 123, "cac_months": 5, "runway_months": 19,
                    "employees": 11, "tam_bn_jpy": 120},
    },
    {
        "id": "fin_012", "name": "TradeDesk AI", "sector": "SMB向け金融インフラ",
        "stage": "Series B", "hq": "東京", "founded": 2018,
        "description": "中小輸出企業向け貿易金融AI。信用状・為替リスク管理を自動化。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 510, "growth_yoy_pct": 82, "gross_margin": 71,
                    "nrr_pct": 117, "cac_months": 17, "runway_months": 26,
                    "employees": 65, "tam_bn_jpy": 900},
    },

    # ══════════════════════════════════════════════════════════════
    # SECTOR 4: サプライチェーン・物流AI
    # ══════════════════════════════════════════════════════════════

    {
        "id": "logi_001", "name": "LogiPath AI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "物流・サプライチェーンAI最適化SaaS。（既投資先）",
        "website": "", "source": "portfolio",
        "metrics": {"arr_mn_jpy": 230, "growth_yoy_pct": 188, "gross_margin": 76,
                    "nrr_pct": 121, "cac_months": 10, "runway_months": 14,
                    "employees": 42, "tam_bn_jpy": 600},
    },
    {
        "id": "logi_002", "name": "InventAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "製造業向けAI需要予測＆在庫最適化。ERP連携。過剰在庫▲35%実績。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 490, "growth_yoy_pct": 95, "gross_margin": 73,
                    "nrr_pct": 120, "cac_months": 14, "runway_months": 22,
                    "employees": 70, "tam_bn_jpy": 800},
    },
    {
        "id": "logi_003", "name": "LastMileAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "大阪", "founded": 2021,
        "description": "宅配ラストマイルAIルート最適化。配達員の生産性+30%。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 200, "growth_yoy_pct": 155, "gross_margin": 69,
                    "nrr_pct": 115, "cac_months": 11, "runway_months": 15,
                    "employees": 32, "tam_bn_jpy": 400},
    },
    {
        "id": "logi_004", "name": "WareBot", "sector": "サプライチェーン・物流AI",
        "stage": "Series B", "hq": "愛知", "founded": 2018,
        "description": "倉庫内ロボット制御AIソフト。既存フォークリフト＋AI制御で自動化。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 680, "growth_yoy_pct": 88, "gross_margin": 72,
                    "nrr_pct": 122, "cac_months": 16, "runway_months": 24,
                    "employees": 88, "tam_bn_jpy": 700},
    },
    {
        "id": "logi_005", "name": "ColdChainAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "東京", "founded": 2020,
        "description": "食品・医薬品コールドチェーン温度管理AI。異常予知とコンプライアンス自動記録。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 165, "growth_yoy_pct": 175, "gross_margin": 77,
                    "nrr_pct": 119, "cac_months": 12, "runway_months": 16,
                    "employees": 28, "tam_bn_jpy": 300},
    },
    {
        "id": "logi_006", "name": "PortAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series B", "hq": "横浜", "founded": 2019,
        "description": "港湾コンテナ物流AIシステム。荷役スケジュール最適化＆遅延予測。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 380, "growth_yoy_pct": 110, "gross_margin": 70,
                    "nrr_pct": 118, "cac_months": 18, "runway_months": 20,
                    "employees": 52, "tam_bn_jpy": 500},
    },
    {
        "id": "logi_007", "name": "ProcureAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "製造業向けAI調達最適化。サプライヤー評価＋価格交渉支援自動化。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 130, "growth_yoy_pct": 200, "gross_margin": 78,
                    "nrr_pct": 117, "cac_months": 13, "runway_months": 17,
                    "employees": 22, "tam_bn_jpy": 350},
    },
    {
        "id": "logi_008", "name": "TransparAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "サプライチェーン可視化AI。ESG・CO2排出量の自動トレーサビリティ。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 95, "growth_yoy_pct": 290, "gross_margin": 80,
                    "nrr_pct": 123, "cac_months": 9, "runway_months": 18,
                    "employees": 18, "tam_bn_jpy": 250},
    },
    {
        "id": "logi_009", "name": "AgriChain", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "宮崎", "founded": 2021,
        "description": "農産物流通AIプラットフォーム。産地→スーパーの直接マッチング＆物流最適化。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 110, "growth_yoy_pct": 235, "gross_margin": 68,
                    "nrr_pct": 114, "cac_months": 10, "runway_months": 14,
                    "employees": 20, "tam_bn_jpy": 200},
    },
    {
        "id": "logi_010", "name": "FreightFlow", "sector": "サプライチェーン・物流AI",
        "stage": "Series B", "hq": "大阪", "founded": 2019,
        "description": "中小運送会社向けAI配車管理＆ドライバー労務管理。2024年問題対応。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 410, "growth_yoy_pct": 105, "gross_margin": 71,
                    "nrr_pct": 116, "cac_months": 12, "runway_months": 20,
                    "employees": 58, "tam_bn_jpy": 450},
    },
    {
        "id": "logi_011", "name": "QualityAI", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "愛知", "founded": 2020,
        "description": "製造業品質検査AI。ライン上の目視検査を画像AIで自動化。不良品▲90%。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 175, "growth_yoy_pct": 168, "gross_margin": 75,
                    "nrr_pct": 120, "cac_months": 11, "runway_months": 16,
                    "employees": 30, "tam_bn_jpy": 300},
    },
    {
        "id": "logi_012", "name": "RetailOps", "sector": "サプライチェーン・物流AI",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "小売チェーン向けAI発注最適化＆ロス削減。POSデータ × 気象API連携。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 140, "growth_yoy_pct": 195, "gross_margin": 76,
                    "nrr_pct": 118, "cac_months": 8, "runway_months": 17,
                    "employees": 24, "tam_bn_jpy": 280},
    },

    # ══════════════════════════════════════════════════════════════
    # SECTOR 5: 法務・バックオフィス自動化
    # ══════════════════════════════════════════════════════════════

    {
        "id": "leg_001", "name": "ContractAI", "sector": "法務・バックオフィス自動化",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "企業向けAI契約書レビュー＆管理SaaS。弁護士事務所API連携。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 550, "growth_yoy_pct": 112, "gross_margin": 82,
                    "nrr_pct": 126, "cac_months": 13, "runway_months": 24,
                    "employees": 78, "tam_bn_jpy": 400},
    },
    {
        "id": "leg_002", "name": "CompliAI", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "金融機関向けAIコンプライアンス監視。取引監視＆規制報告自動化。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 230, "growth_yoy_pct": 158, "gross_margin": 80,
                    "nrr_pct": 128, "cac_months": 16, "runway_months": 20,
                    "employees": 38, "tam_bn_jpy": 350},
    },
    {
        "id": "leg_003", "name": "HRAutomate", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "中堅企業向けAI人事労務自動化（採用〜退職まで）。電子署名連携。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 185, "growth_yoy_pct": 172, "gross_margin": 78,
                    "nrr_pct": 116, "cac_months": 10, "runway_months": 16,
                    "employees": 32, "tam_bn_jpy": 250},
    },
    {
        "id": "leg_004", "name": "PatentAI", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2020,
        "description": "特許事務所向けAI明細書作成支援＆先行技術調査自動化。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 145, "growth_yoy_pct": 190, "gross_margin": 83,
                    "nrr_pct": 122, "cac_months": 12, "runway_months": 18,
                    "employees": 24, "tam_bn_jpy": 180},
    },
    {
        "id": "leg_005", "name": "DocuFlow", "sector": "法務・バックオフィス自動化",
        "stage": "Series B", "hq": "東京", "founded": 2018,
        "description": "企業向けAIドキュメント管理＆承認ワークフロー。電子帳簿保存法対応。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 620, "growth_yoy_pct": 92, "gross_margin": 79,
                    "nrr_pct": 120, "cac_months": 11, "runway_months": 26,
                    "employees": 85, "tam_bn_jpy": 500},
    },
    {
        "id": "leg_006", "name": "AuditBot", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "大阪", "founded": 2021,
        "description": "中堅企業向けAI内部監査自動化。リスク評価＆監査証跡の自動生成。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 105, "growth_yoy_pct": 250, "gross_margin": 81,
                    "nrr_pct": 125, "cac_months": 14, "runway_months": 17,
                    "employees": 19, "tam_bn_jpy": 200},
    },
    {
        "id": "leg_007", "name": "PrivacyGuard", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "企業向けAI個人情報管理（改正個人情報保護法対応）。自動マスキング。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 80, "growth_yoy_pct": 340, "gross_margin": 84,
                    "nrr_pct": 121, "cac_months": 8, "runway_months": 19,
                    "employees": 15, "tam_bn_jpy": 150},
    },
    {
        "id": "leg_008", "name": "DisputeAI", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "法律事務所向けAI訴訟戦略支援＆判例検索。弁護士の初期調査▲70%。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 120, "growth_yoy_pct": 210, "gross_margin": 82,
                    "nrr_pct": 119, "cac_months": 11, "runway_months": 15,
                    "employees": 21, "tam_bn_jpy": 160},
    },
    {
        "id": "leg_009", "name": "RegTrack", "sector": "法務・バックオフィス自動化",
        "stage": "Series B", "hq": "東京", "founded": 2019,
        "description": "製薬・食品・金融向けAI規制変更モニタリング＆対応タスク管理。",
        "website": "", "source": "bridge",
        "metrics": {"arr_mn_jpy": 370, "growth_yoy_pct": 118, "gross_margin": 81,
                    "nrr_pct": 124, "cac_months": 15, "runway_months": 22,
                    "employees": 50, "tam_bn_jpy": 300},
    },
    {
        "id": "leg_010", "name": "CorpSec AI", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "上場企業向けAI株主総会準備＆開示書類自動化。IR部門の工数▲60%。",
        "website": "", "source": "pr_times",
        "metrics": {"arr_mn_jpy": 90, "growth_yoy_pct": 300, "gross_margin": 83,
                    "nrr_pct": 122, "cac_months": 10, "runway_months": 17,
                    "employees": 16, "tam_bn_jpy": 120},
    },
    {
        "id": "leg_011", "name": "SourcingCheck", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2021,
        "description": "企業向けサプライヤーコンプライアンスAI（人権DD・ESG）。欧州規制対応。",
        "website": "", "source": "initial",
        "metrics": {"arr_mn_jpy": 160, "growth_yoy_pct": 185, "gross_margin": 79,
                    "nrr_pct": 118, "cac_months": 13, "runway_months": 16,
                    "employees": 27, "tam_bn_jpy": 220},
    },
    {
        "id": "leg_012", "name": "MeetingMind", "sector": "法務・バックオフィス自動化",
        "stage": "Series A", "hq": "東京", "founded": 2022,
        "description": "企業向けAI議事録自動生成＆アクション管理。Zoom/Teams統合。",
        "website": "", "source": "wantedly",
        "metrics": {"arr_mn_jpy": 65, "growth_yoy_pct": 420, "gross_margin": 85,
                    "nrr_pct": 113, "cac_months": 4, "runway_months": 21,
                    "employees": 12, "tam_bn_jpy": 100},
    },
]


# ── LP seed data ──────────────────────────────────────────────────────────────

LP_SEED: list[dict] = [
    {"org_name": "東北みらい銀行", "contact_name": "佐々木部長", "contact_email": "sasaki@tohoku-mirai-bank.example.com",
     "tier": "tier1", "lp_type": "地方銀行", "ticket_mn_jpy": 300, "status": "meeting_scheduled",
     "notes": "来週木曜10時zoom。日本政策投資銀行経由。代替投資枠30億円を新設。初めてのPEファンド投資候補。"},
    {"org_name": "Sony Innovation Fund", "contact_name": "田村VP", "contact_email": "tamura@sony-if.example.com",
     "tier": "tier1", "lp_type": "事業法人CVC", "ticket_mn_jpy": 500, "status": "met",
     "notes": "先週初回面談済。医療・介護AIへの戦略的関心あり。DD資料送付待ち。"},
    {"org_name": "田中ファミリーオフィス", "contact_name": "田中太郎", "contact_email": "tanaka@tanaka-fo.example.com",
     "tier": "tier2", "lp_type": "ファミリーオフィス", "ticket_mn_jpy": 200, "status": "intro_sent",
     "notes": "3日前メール送付済み。返信待ち。製造業創業家。"},
    {"org_name": "関西電力企業年金基金", "contact_name": "松本理事", "contact_email": "matsumoto@kepf.example.or.jp",
     "tier": "tier2", "lp_type": "企業年金", "ticket_mn_jpy": 500, "status": "prospect",
     "aum_bn_jpy": 80, "pe_alloc_pct": 0, "pe_target_pct": 5,
     "notes": "代替投資比率5→8%引き上げ方針を発表。未コンタクト。PE初投資検討中。"},
    {"org_name": "Sequoia Heritage（アジア枠）", "contact_name": "James Chen", "contact_email": "jchen@seq-heritage.example.com",
     "tier": "tier3", "lp_type": "外資機関投資家", "ticket_mn_jpy": 1000, "status": "met",
     "aum_bn_jpy": None, "pe_alloc_pct": None, "pe_target_pct": None,
     "notes": "4月面談済み。5週間放置中。ファーストクローズ後に再アプローチが現実的。"},

    # ── 年金ファンド拡充 ──────────────────────────────────────────────────────────
    {"org_name": "トヨタ自動車企業年金基金", "contact_name": "高橋CIO", "contact_email": "takahashi@toyota-pf.example.or.jp",
     "tier": "tier1", "lp_type": "企業年金", "ticket_mn_jpy": 2000, "status": "prospect",
     "aum_bn_jpy": 800, "pe_alloc_pct": 3.2, "pe_target_pct": 8,
     "notes": "AUM 8,000億円。PE配分を3.2%→8%に引き上げ方針。国内成長株PEへの初投資を検討中。CIO経由でアプローチ予定。"},
    {"org_name": "NTTグループ企業年金基金", "contact_name": "伊藤常務", "contact_email": "ito@ntt-pension.example.or.jp",
     "tier": "tier1", "lp_type": "企業年金", "ticket_mn_jpy": 3000, "status": "intro_sent",
     "aum_bn_jpy": 1200, "pe_alloc_pct": 2.5, "pe_target_pct": 6,
     "notes": "AUM 1.2兆円、日本最大規模の企業年金の一つ。2週間前にLP向け資料送付済み。返信待ち。DX推進中でテックPEに関心。"},
    {"org_name": "ソニーグループ企業年金基金", "contact_name": "中村理事長", "contact_email": "nakamura@sony-pension.example.or.jp",
     "tier": "tier1", "lp_type": "確定給付企業年金", "ticket_mn_jpy": 1500, "status": "met",
     "aum_bn_jpy": 300, "pe_alloc_pct": 4.0, "pe_target_pct": 10,
     "notes": "先月初回面談。PE配分積極的、目標10%。医療AI・エンタメテックを戦略テーマに合致として評価。DD資料送付中。"},
    {"org_name": "日立グループ企業年金基金", "contact_name": "小林部長", "contact_email": "kobayashi@hitachi-pension.example.or.jp",
     "tier": "tier2", "lp_type": "企業年金", "ticket_mn_jpy": 1000, "status": "prospect",
     "aum_bn_jpy": 450, "pe_alloc_pct": 1.8, "pe_target_pct": 5,
     "notes": "AUM 4,500億円。製造DX・サプライチェーンAIへの戦略的関心と合致。未コンタクト。インフラ系VCへの実績あり。"},
    {"org_name": "NEC企業年金基金", "contact_name": "山田専務理事", "contact_email": "yamada@nec-pension.example.or.jp",
     "tier": "tier2", "lp_type": "企業年金", "ticket_mn_jpy": 800, "status": "meeting_scheduled",
     "aum_bn_jpy": 200, "pe_alloc_pct": 2.0, "pe_target_pct": 7,
     "notes": "来月15日に面談設定済み。NECとの事業シナジーも議論予定。SaaS・AI特化PEへの初投資を真剣検討。"},
    {"org_name": "地方公務員共済組合連合会", "contact_name": "渡辺理事", "contact_email": "watanabe@laicpf.example.or.jp",
     "tier": "tier1", "lp_type": "共済組合", "ticket_mn_jpy": 2500, "status": "prospect",
     "aum_bn_jpy": 500, "pe_alloc_pct": 1.0, "pe_target_pct": 3,
     "notes": "AUM 5,000億円。PE配分1%→3%引き上げ方針。コンプライアンス基準が厳しく時間軸長め。中長期候補。"},
    {"org_name": "キヤノン企業年金基金", "contact_name": "斉藤CIO", "contact_email": "saito@canon-pension.example.or.jp",
     "tier": "tier2", "lp_type": "確定給付企業年金", "ticket_mn_jpy": 600, "status": "intro_sent",
     "aum_bn_jpy": 120, "pe_alloc_pct": 3.5, "pe_target_pct": 8,
     "notes": "AUM 1,200億円。PE経験あり（海外VC実績）。国内成長株PEは初挑戦。製造・医療機器テック関心高。"},
    {"org_name": "パナソニック企業年金基金", "contact_name": "田辺副理事長", "contact_email": "tanabe@panasonic-pension.example.or.jp",
     "tier": "tier2", "lp_type": "企業年金", "ticket_mn_jpy": 700, "status": "prospect",
     "aum_bn_jpy": 280, "pe_alloc_pct": 2.2, "pe_target_pct": 6,
     "notes": "AUM 2,800億円。スマートファクトリー・物流AI分野の投資実績あり。Pyreneeのサプライチェーン案件に関心。"},
    {"org_name": "大阪市職員共済組合", "contact_name": "藤本理事", "contact_email": "fujimoto@osaka-city-kyosai.example.or.jp",
     "tier": "tier2", "lp_type": "共済組合", "ticket_mn_jpy": 400, "status": "prospect",
     "aum_bn_jpy": 80, "pe_alloc_pct": 0, "pe_target_pct": 2,
     "notes": "AUM 800億円。PE投資初挑戦予定。大阪府・市のスタートアップ支援政策と方向性合致。議会承認が必要。"},
    {"org_name": "住友グループ企業年金連合会", "contact_name": "井上専務", "contact_email": "inoue@sumitomo-pension.example.or.jp",
     "tier": "tier2", "lp_type": "基金型企業年金", "ticket_mn_jpy": 900, "status": "met",
     "aum_bn_jpy": 150, "pe_alloc_pct": 5.0, "pe_target_pct": 10,
     "notes": "AUM 1,500億円。PE配分5%→10%の積極姿勢。2週間前に面談済み。医療・金融インフラ領域の関心強い。"},
]
